# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DailyMotd < Formula
  desc "Generic daily terminal message-of-the-day CLI. Ships with Today in Nature."
  homepage "https://github.com/mennoliefstingh/daily-motd"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mennoliefstingh/daily-motd/releases/download/v0.1.4/daily-motd_0.1.4_darwin_amd64.tar.gz"
      sha256 "10eb4ce4e265e2b3f95272798fb6b1234e0cac101691c250a800ade95d0434b0"

      define_method(:install) do
        bin.install "daily-motd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mennoliefstingh/daily-motd/releases/download/v0.1.4/daily-motd_0.1.4_darwin_arm64.tar.gz"
      sha256 "98b36e9c2e42fc1e8deb44b89bfee15c7b8fcf85f18bec279d00136ecf30d03d"

      define_method(:install) do
        bin.install "daily-motd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mennoliefstingh/daily-motd/releases/download/v0.1.4/daily-motd_0.1.4_linux_amd64.tar.gz"
      sha256 "48784528e67aced7b22684577bb95a7da0427ca34c3d8c0f637a4658dc0e3106"
      define_method(:install) do
        bin.install "daily-motd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mennoliefstingh/daily-motd/releases/download/v0.1.4/daily-motd_0.1.4_linux_arm64.tar.gz"
      sha256 "50858c8a65749f328ec04b11f298d07679a263b2cd84293f4f4ebdb023e1bfb1"
      define_method(:install) do
        bin.install "daily-motd"
      end
    end
  end

  test do
    system "#{bin}/daily-motd", "--version"
  end
end
