# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DailyMotd < Formula
  desc "Generic daily terminal message-of-the-day CLI. Ships with Today in Nature."
  homepage "https://github.com/mennoliefstingh/daily-motd"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mennoliefstingh/daily-motd/releases/download/v0.1.5/daily-motd_0.1.5_darwin_amd64.tar.gz"
      sha256 "ec3afa8705869f071e54f7aa84781340877785ad8406cfdde98d1e440f0da524"

      define_method(:install) do
        bin.install "daily-motd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mennoliefstingh/daily-motd/releases/download/v0.1.5/daily-motd_0.1.5_darwin_arm64.tar.gz"
      sha256 "78b0266a149eb36fb0d9b2f3260bd32fefb12194404ce0ad77551a0da3b778d4"

      define_method(:install) do
        bin.install "daily-motd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mennoliefstingh/daily-motd/releases/download/v0.1.5/daily-motd_0.1.5_linux_amd64.tar.gz"
      sha256 "3f03022e93f554923570af729849ec8f909bd04545bbb78196109335f2685f2a"
      define_method(:install) do
        bin.install "daily-motd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mennoliefstingh/daily-motd/releases/download/v0.1.5/daily-motd_0.1.5_linux_arm64.tar.gz"
      sha256 "80e4bdd5eb330f0921d9acffa6b21d5cbf48ee7c35c7676e105a099d7c51afd1"
      define_method(:install) do
        bin.install "daily-motd"
      end
    end
  end

  test do
    system "#{bin}/daily-motd", "--version"
  end
end
