# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DailyMotd < Formula
  desc "Generic daily terminal message-of-the-day CLI. Ships with Today in Nature."
  homepage "https://github.com/mennoliefstingh/daily-motd"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mennoliefstingh/daily-motd/releases/download/v0.1.6/daily-motd_0.1.6_darwin_amd64.tar.gz"
      sha256 "ebebba463229a1cd286b0823402fd2e2f97b1ba14f3c39e76249f8cd36b6613d"

      define_method(:install) do
        bin.install "daily-motd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mennoliefstingh/daily-motd/releases/download/v0.1.6/daily-motd_0.1.6_darwin_arm64.tar.gz"
      sha256 "d44a2aeb45a7faf4466928fcb3e041fde036847e0d113bf7ea8ab83f250a5179"

      define_method(:install) do
        bin.install "daily-motd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mennoliefstingh/daily-motd/releases/download/v0.1.6/daily-motd_0.1.6_linux_amd64.tar.gz"
      sha256 "70451ac3790236854d3e35067600ee1da72fbe3174aafce2380e16273d7d46d8"
      define_method(:install) do
        bin.install "daily-motd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mennoliefstingh/daily-motd/releases/download/v0.1.6/daily-motd_0.1.6_linux_arm64.tar.gz"
      sha256 "825e69734e8e7d9c7018e5bd5c5448152fea05da79e94ff31b90ab8bfc567b11"
      define_method(:install) do
        bin.install "daily-motd"
      end
    end
  end

  test do
    system "#{bin}/daily-motd", "--version"
  end
end
